/**
 * @file embx_ir_rx_gpio.c
 * @date 10/11/2018
 * @author: bbernath
 * @copyright Copyright (C) 2018 Brett Bernath. All Rights Reserved.
 *
 * @brief The embx_ir_rx_gpio module handles the input pin connected to an IR receiver.
 * @details - This module configures a GPIO pin to act as an EXTINT channel where 
 *            the pin will generate an interrupt based upon a rising or falling edge
 *            generated by the IR receiver.
 *            The module provides methods to initialize, enable, and disable the EXTINT channel.  It also provides a 
 *            callback function that handles the rising or falling edge events.  The call back function simply
 *            calls the embx_rx_ir_phy_state_machine.  The state machine handles the event.  
*/ 
#include <asf.h>
#include "embx/embx_ir/embx_ir_rx_phy.h"
#include "embx/embx_ir/embx_ir_rx_gpio.h"

/** Module statistics */
static embx_ir_rx_gpio_stats_t embx_ir_rx_gpio_stats = {0, 0};

/** The configuration is saved to allow the module to be enabled and disabled */
static struct extint_chan_conf config_extint_chan;

/** @brief Reset the module's statistics */
static void embx_ir_rx_gpio_reset_stats(void)
{
	embx_ir_rx_gpio_stats.falling_edge_events = 0;
	embx_ir_rx_gpio_stats.rising_edge_events = 0;	
}

/** 
* @brief The callback is generated in response to a rising or falling edge on the GPIO pin.
* @details - The callback function determines if a rising or falling edge occured and
* triggers the state machine with the appropriate input.
*/
static void embx_ir_rx_gpio_callback(void)
{
	uint8_t channel = extint_get_current_channel();
	bool pin_state = port_pin_get_input_level(EMBX_IR_RX_EIC_PIN);
	if( pin_state == true ) { /* Rising Edge -> Mark Ended, SPACE started or Packet Ended */ 
		embx_rx_ir_phy_state_machine(EMBX_IR_RX_GPIO_EVENT_RISING_EDGE);
		embx_ir_rx_gpio_stats.rising_edge_events++; 
	} else { /* FALLING Edge -> Mark started, Space ended */ 
		embx_rx_ir_phy_state_machine(EMBX_IR_RX_GPIO_EVENT_FALLING_EDGE);
		embx_ir_rx_gpio_stats.falling_edge_events++; 		 
	}
	extint_chan_clear_detected(channel);
}

/**
* @brief Initializes the module.
* @details Resets the statistics, configures the EXTINT channel gpio pin to trigger events on both rising and falling
* edges, and uses an internal pullup resistor.  Registers the callback, but does not enable it.
* The enable function (see below) enables the callback and allows the module to function.
*/
void embx_ir_rx_gpio_init(void)
{
	embx_ir_rx_gpio_reset_stats();	
	
	extint_chan_get_config_defaults(&config_extint_chan);

	/* Configure the GPIO pin for use as an external interrupt input */
	config_extint_chan.gpio_pin = EMBX_IR_RX_EIC_PIN;
	config_extint_chan.gpio_pin_mux = EMBX_IR_RX_EIC_MUX;
	config_extint_chan.gpio_pin_pull = EXTINT_PULL_UP;
	config_extint_chan.detection_criteria = EXTINT_DETECT_BOTH; /* Both edges */	
	config_extint_chan.filter_input_signal = true;
	
	extint_chan_set_config(EMBX_IR_RX_EIC_CHANNEL, &config_extint_chan);

	extint_register_callback(embx_ir_rx_gpio_callback, EMBX_IR_RX_EIC_CHANNEL, EXTINT_CALLBACK_TYPE_DETECT);
}

/** @brief - Enables the module.*/
void embx_ir_rx_gpio_enable(void)
{
	extint_chan_enable_callback(EMBX_IR_RX_EIC_CHANNEL, EXTINT_CALLBACK_TYPE_DETECT);	
}

/** @brief - Disables the module. */
void embx_ir_rx_gpio_disable(void)
{
	extint_chan_disable_callback(EMBX_IR_RX_EIC_CHANNEL, EXTINT_CALLBACK_TYPE_DETECT);
}
